### ISSUE TITLE
Unable to join as commander after server dropped client connections

### ISSUE THREAD

**Issue by drspod** [data-bomb/Silica_ListenServer#1] opened 2023-06-13 18:05 UTC
We had a situation today on the Kane HvA server which was running the **Commander Management** mod.

It's not possible to know whether this bug was caused by a bug in Silica, or in the mod, but I will describe it here in case it is possibly a logic error in the Commander Management mod.

A new game was started, Commanders were selected. 6 minutes into the game, the server for some reason dropped all client connections.

When we reconnected to the server, the game was still proceeding as usual. The original Alien commander chose not to reconnect and resume the game.

When any other player selected **Aliens** the two options were given for Infantry or Commander. But upon clicking Commander, the player was spawned as infantry, and the player list showed that still nobody was Commander of Aliens.

The Human team did not have this problem, possibly because the player who was previously Commander of the Humans had reconnected to the server. Humans were able to select the Commander role and command as usual.

**Steps to Reproduce**: Start a game using the Commander Management application system. Kill all the client connections so every client drops. Have clients rejoin the game with the exception of the chosen commanders and see if any of the reconnected clients can take the commander role.

**Expected Behavior**: If the selected Commander is disconnected from the server through a dropped network connection (instead of by manually leaving the game) then any other player should be allowed to select the Commander role.

**Comment by data-bomb** [comment] 2023-06-14 03:01
Commander Management would block and send a player to infantry during the first 30 seconds or if the player was commander banned. If the mod considered it within the first 30 seconds because all players left then you would see a message in chat `[BOT] <playername> has applied for commander.` as soon as block occurred. Also inspect the `MelonLoader\Latest.log` file to see if the player was blocked due a commander ban. It's unclear how to reproduce since the behavior that dropped clients is not known.

**Comment by drspod** [comment] 2023-06-14 15:18
Just today I saw somebody report this same issue on the Prime Battalion server, and they are not running the Commander Management mod. I'm waiting on them to respond with which mods exactly they are running. 

I would be inclined to assume that this is a bug in the game itself and close as "can't reproduce." The logs from yesterday are no longer available and I'm certain that the cause was not a commander ban and there were no messages in the chat from the BOT.

**Comment by data-bomb** [comment] 2023-06-14 17:53
Closing for now. If there's additional information from a log then let's re-visit.

**Closed by data-bomb** 2023-06-14 17:53 UTC
Labels: question, gamebug
